version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      HALO_DATA_DIR: /app/data
    volumes:
      - ./data:/app/data   # mount your Excel inputs
    ports:
      - "8000:8000"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        VITE_API_BASE: /api   # frontend will call /api/*
    ports:
      - "5173:80"            # view app at http://localhost:5173
    depends_on:
      - api
    restart: unless-stopped
