[email]
smtp_host = "smtp.office365.com"
smtp_port = 587
username  = "emailaipoc@skitinfra.cloud"
password  = "***** APP PASSWORD OR O365 PASSWORD *****"
sender    = "emailaipoc@skitinfra.cloud"

# People that appear in the dropdown (you can add more)
recipients = [
  "you@aptia.com",
  "manager@aptia.com",
  "qualitylead@aptia.com"
]
