# .streamlit/secrets.toml

[graph]
tenant_id     = "6436ad09-c020-4f2a-a8c8-2300e2d50f9d"
client_id     = "ea11fcc3-20ea-4812-b661-d32bd90ed0ea"
client_secret = "1Ls8Q~UEmQFzDmIJ4qCQNcKPepwQgvasPncbHaB9"
mailbox       = "emailaipoc@skitinfra.cloud"

# People that appear in the dropdown (you can add more)
recipients = [
  "you@aptia.com",
  "manager@aptia.com",
  "qualitylead@aptia.com"
]
